const SET_ALL_PROPERTIES = 'SET_ALL_PROPERTIES'
const ADD_NEW_PROPERTY = 'ADD_NEW_PROPERTY'
const UPDATE_PROPERTY_DETAILS = 'UPDATE_PROPERTY_DETAILS'
const DELETE_PROPERTY = 'DELETE_PROPERTY'

const ADD_NEW_ROOM = 'ADD_NEW_ROOM'

export {
   SET_ALL_PROPERTIES,
   ADD_NEW_PROPERTY,
   UPDATE_PROPERTY_DETAILS,
   DELETE_PROPERTY,
   ADD_NEW_ROOM,
}
