const SET_ALL_REQUESTS = 'SET_ALL_REQUESTS'
const ADD_NEW_REQUEST = 'ADD_NEW_REQUEST'
const UPDATE_REQUEST_DETAILS = 'UPDATE_REQUEST_DETAILS'
const DELETE_REQUEST = 'DELETE_REQUEST'

export {
   SET_ALL_REQUESTS,
   ADD_NEW_REQUEST,
   UPDATE_REQUEST_DETAILS,
   DELETE_REQUEST,
}
