const SET_ALL_ITEMS = 'SET_ALL_ITEMS'
const ADD_NEW_ITEM = 'ADD_NEW_ITEM'
const UPDATE_ITEM_DETAILS = 'UPDATE_ITEM_DETAILS'
const DELETE_ITEM = 'DELETE_ITEM'

export { SET_ALL_ITEMS, ADD_NEW_ITEM, UPDATE_ITEM_DETAILS, DELETE_ITEM }
